Repository GOMINTAPA/GMTP, pull requests merged in 2024-07, with the labels that each got.

#6 로그인 화면 구성
  gomintapa/assets/images/gmtp_logo_big.png
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/login.dart
  gomintapa/lib/src/widgets/forms/label_textfield.dart
  gomintapa/pubspec.yaml
Labels: 🎨ui, 🌟frontend

#7 Docs: 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/refactor-issue-template.md
  .github/ISSUE_TEMPLATE/ui-issue-template.md
Labels: 📑docs

#8 docs: readme에 commit 타입 명시
  README.md
Labels: 📑docs

#11 홈 화면 구성
  gomintapa/assets/images/gomintapa_logo.png
  gomintapa/assets/images/home.png
  gomintapa/assets/images/home_selected.png
  gomintapa/assets/images/makmak.png
  gomintapa/assets/images/makmak_selected.png
  gomintapa/assets/images/tangtang.png
  gomintapa/assets/images/tangtang_selected.png
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/feed/index.dart
  gomintapa/lib/src/screens/home.dart
  gomintapa/lib/src/widgets/buttons/create_post_button.dart
  gomintapa/lib/src/widgets/buttons/filter_button.dart
  gomintapa/lib/src/widgets/navigation/app_bar.dart
  gomintapa/lib/src/widgets/navigation/bottom_navigation_bar.dart
  gomintapa/lib/src/widgets/sections/filter_section.dart
  gomintapa/pubspec.yaml
Labels: 🎨ui, ♻️refactor, 🌟frontend

#13 feat: 서버 폴더 만들기 및 초기설정
  gomintapa_server/package.json
Labels: ✨feat, 🔥backend

#14 .gitattribute 파일을 추가하여 리포지토리 언어 설정
  .gitattribute
Labels: ⚙️setting

#17 setting: .gitattributes 파일 추가 및 언어 설정
  .gitattributes
Labels: ⚙️setting

#22 refactor: 상단바 재사용
  gomintapa/lib/src/screens/home.dart
  gomintapa/lib/src/widgets/navigation/back_app_bar.dart
  gomintapa/lib/src/widgets/navigation/form_action_app_bar.dart
  gomintapa/lib/src/widgets/navigation/home_app_bar.dart
  gomintapa/lib/src/widgets/sections/app_bar_section.dart
Labels: 🎨ui, ♻️refactor, 🌟frontend

#23 UI: 키워드 선택 화면 구성
  gomintapa/lib/src/screens/feed/feed_index.dart
  gomintapa/lib/src/screens/feed/index.dart
  gomintapa/lib/src/screens/home.dart
  gomintapa/lib/src/widgets/sections/filter_bar_section.dart
Labels: 🎨ui, 🌟frontend

#26 refactor: 필터 선택 화면
  gomintapa/lib/src/screens/feed/feed_index.dart
  gomintapa/lib/src/shared/keyword_data.dart
  gomintapa/lib/src/widgets/buttons/filter_sheet_button.dart
  gomintapa/lib/src/widgets/sections/filter_sheet.dart
Labels: 🎨ui, ♻️refactor, 🌟frontend

#28 UI: 마이페이시 화면 구성
  gomintapa/assets/images/default_profile.png
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/models/user_model.dart
  gomintapa/lib/src/screens/auth/login.dart
  gomintapa/lib/src/screens/auth/register.dart
  gomintapa/lib/src/screens/my/mypage.dart
  gomintapa/lib/src/widgets/buttons/logout.button.dart
  gomintapa/lib/src/widgets/sections/my/bottom_section.dart
  gomintapa/lib/src/widgets/sections/my/concern_feed_section.dart
  gomintapa/lib/src/widgets/sections/my/user_section.dart
  gomintapa/pubspec.yaml
Labels: 🎨ui, 🌟frontend

#30 refactor : 마이페이지 화면
  gomintapa/lib/src/screens/my/mypage.dart
  gomintapa/lib/src/widgets/sections/my/concern_feed_section.dart
  gomintapa/lib/src/widgets/sections/my/concern_tab_bar.dart
  gomintapa/lib/src/widgets/sections/my/concern_tab_bar_view.dart
Labels: ♻️refactor, 🌟frontend

#31 feat: 선택한 키워드 표시
  gomintapa/lib/src/screens/feed/feed_index.dart
  gomintapa/lib/src/widgets/buttons/filter_sheet_button.dart
  gomintapa/lib/src/widgets/sections/filter_bar_section.dart
  gomintapa/lib/src/widgets/sections/filter_sheet.dart
Labels: 🎨ui, ✨feat, 🌟frontend

#34 feat: 버튼 클릭시 페이지 이동 기능 구현
  gomintapa/lib/src/widgets/navigation/back_app_bar.dart
  gomintapa/lib/src/widgets/navigation/home_app_bar.dart
Labels: ✨feat, 🌟frontend

#38 UI: 고민 카드 디자인
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/feed/feed_index.dart
  gomintapa/lib/src/widgets/listitems/concern_list_item.dart
Labels: 🎨ui, 🌟frontend

#41 UI: 고민 작성 화면 구성
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/post/create_post.dart
  gomintapa/lib/src/widgets/forms/a_input.dart
  gomintapa/lib/src/widgets/forms/b_input.dart
  gomintapa/lib/src/widgets/forms/custom_input.dart
  gomintapa/lib/src/widgets/forms/photo_attachment.dart
  gomintapa/lib/src/widgets/sections/post/choices_section.dart
  gomintapa/lib/src/widgets/sections/post/input_section.dart
Labels: 🎨ui, ♻️refactor, 🌟frontend

#46 refactor: 키워드 선택 섹션 분리
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/my/mypage.dart
  gomintapa/lib/src/screens/post/create_post.dart
  gomintapa/lib/src/widgets/buttons/keyword_select_button.dart
  gomintapa/lib/src/widgets/sections/my/bottom_section.dart
Labels: 🎨ui, ♻️refactor, 🌟frontend

#48 Feat: 해결탕탕 컬러 변경 기능 구현
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/feed/tang_feed_index.dart
  gomintapa/lib/src/widgets/listitems/tang_list_item.dart
Labels: ✨feat, 🌟frontend

#60 UI: 상세 페이지 구현
  gomintapa/assets/images/dog.jpg
  gomintapa/assets/images/jjanggu.jpg
  gomintapa/assets/images/walk_dog.jpg
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/post/create_post.dart
  gomintapa/lib/src/screens/post/post_detail.dart
  gomintapa/pubspec.yaml
Labels: 🎨ui, 🌟frontend

#62 feat: TextField의 keyboardType 변경
  gomintapa/lib/src/screens/auth/login.dart
  gomintapa/lib/src/screens/auth/register.dart
  gomintapa/lib/src/widgets/forms/label_textfield.dart
Labels: ✨feat, 🌟frontend

#63 feat: 상세페이지 구현 화면 연결 완료
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/feed/feed_index.dart
  gomintapa/lib/src/widgets/listitems/concern_list_item.dart
Labels: ✨feat

#67 refactor: 상세페이지 섹션 분리
  gomintapa/lib/src/controllers/auth_controller.dart
  gomintapa/lib/src/controllers/feed_controller.dart
  gomintapa/lib/src/home.dart
  gomintapa/lib/src/screens/auth/login.dart
  gomintapa/lib/src/screens/auth/register.dart
  gomintapa/lib/src/screens/post/create_post.dart
  gomintapa/lib/src/screens/post/post_detail.dart
  gomintapa/lib/src/widgets/forms/input/a_input.dart
  gomintapa/lib/src/widgets/forms/input/b_input.dart
  gomintapa/lib/src/widgets/forms/input/custom_input.dart
  gomintapa/lib/src/widgets/forms/input/label_textfield.dart
  gomintapa/lib/src/widgets/forms/input/photo_attachment.dart
  gomintapa/lib/src/widgets/sections/display/choices/choices_section.dart
  gomintapa/lib/src/widgets/sections/display/choices/photo_display.dart
  gomintapa/lib/src/widgets/sections/display/choices/text_display.dart
  gomintapa/lib/src/widgets/sections/display/content_section.dart
  gomintapa/lib/src/widgets/sections/display/profile_section.dart
  gomintapa/lib/src/widgets/sections/post/choices_input_section.dart
Labels: ♻️refactor

#69 bug: 앱 재시작 시 로그인 안하도록 고침
  gomintapa/lib/src/controllers/auth_controller.dart
  gomintapa/lib/src/providers/provider.dart
Labels: 🐛fixBug

#71 Update pubspec.yaml
  gomintapa/pubspec.yaml
Labels: 🐛fixBug

#72 Update pubspec.lock
  gomintapa/pubspec.lock
Labels: 🐛fixBug

#74 리팩토링 완료
  gomintapa/lib/src/controllers/auth_controller.dart
  gomintapa/lib/src/providers/auth_provider.dart
Labels: ♻️refactor

#75 feat: 선택한 키워드 표시 완료
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/feed/feed_index.dart
  gomintapa/lib/src/screens/feed/mak_feed_index.dart
  gomintapa/lib/src/screens/feed/tang_feed_index.dart
  gomintapa/lib/src/screens/post/create_post.dart
  gomintapa/lib/src/screens/post/post_detail.dart
  gomintapa/lib/src/utils/dialogs/dialog_util.dart
  gomintapa/lib/src/utils/dialogs/field_validation_util.dart
  gomintapa/lib/src/utils/dialogs/post_submission_util.dart
  gomintapa/lib/src/utils/dialogs/unsaved_changes_dialog_util.dart
  gomintapa/lib/src/utils/modals/keyword_modal_util.dart
  gomintapa/lib/src/widgets/buttons/keyword_button.dart
  gomintapa/lib/src/widgets/buttons/keyword_chip/keyword_chip.dart
  gomintapa/lib/src/widgets/buttons/keyword_chip/removable_keyword_chip.dart
  gomintapa/lib/src/widgets/navigation/back_app_bar.dart
  gomintapa/lib/src/widgets/navigation/form_action_app_bar.dart
  gomintapa/lib/src/widgets/navigation/home_app_bar.dart
  gomintapa/lib/src/widgets/sections/display/keyword_section.dart
  gomintapa/lib/src/widgets/sections/feed/app_bar_section.dart
  gomintapa/lib/src/widgets/sections/feed/filter_bar_section.dart
  gomintapa/lib/src/widgets/sections/filter_bar_section.dart
  gomintapa/lib/src/widgets/sections/keyword/keyword_list_modal.dart
  gomintapa/lib/src/widgets/sections/post/removable_keyword_section.dart
Labels: ✨feat, ♻️refactor

#78 comment: app.dart 파일 초기 경로 원래대로 수정
  gomintapa/lib/src/app.dart
Labels: ♻️refactor

#77 feat: 로그아웃 기능 완료
  gomintapa/lib/src/providers/feed_provider.dart
  gomintapa/lib/src/screens/auth/login.dart
  gomintapa/lib/src/screens/my/mypage.dart
Labels: ✨feat, 🌟frontend

#84 Bug: 고민 작성 페이지 제출 버그 해결
  gomintapa/lib/src/screens/post/create_post.dart
  gomintapa/lib/src/utils/dialogs/post_submission_util.dart
Labels: 🐛fixBug, 🌟frontend

#86 Feat/80 : 정보수정 기능 완료
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/controllers/user_controller.dart
  gomintapa/lib/src/home.dart
  gomintapa/lib/src/models/user_model.dart
  gomintapa/lib/src/providers/user_provider.dart
  gomintapa/lib/src/screens/feed/mak_feed_index.dart
  gomintapa/lib/src/screens/feed/tang_feed_index.dart
  gomintapa/lib/src/screens/my/mypage.dart
  gomintapa/lib/src/screens/my/mypage_edit.dart
  gomintapa/lib/src/widgets/sections/my/user_section.dart
Labels: ✨feat, 🌟frontend, 🔥backend

#88 UI: 피드 화면의 상단 하단 고정 영역 제거
  gomintapa/lib/src/screens/feed/feed_index.dart
  gomintapa/lib/src/screens/feed/mak_feed_index.dart
  gomintapa/lib/src/screens/feed/tang_feed_index.dart
  gomintapa/lib/src/widgets/buttons/create_post_button.dart
  gomintapa/lib/src/widgets/listitems/concern_list_item.dart
  gomintapa/lib/src/widgets/listitems/mak_list_item.dart
  gomintapa/lib/src/widgets/listitems/tang_list_item.dart
Labels: 🎨ui, 🌟frontend

#89 feat: 상세페이지에서 수정, 삭제, 고민해결 선택할 수 있게 구현
  gomintapa/lib/src/app.dart
  gomintapa/lib/src/screens/post/post_detail.dart
  gomintapa/lib/src/widgets/listitems/concern_list_item.dart
  gomintapa/lib/src/widgets/sections/display/profile_section.dart
Labels: 🎨ui, ✨feat, 🌟frontend

#91 feat: 마이페이지 정보영역 기능 추가
  .idea/misc.xml
  .idea/workspace.xml
  gomintapa/assets/images/none_post.png
  gomintapa/lib/src/controllers/user_controller.dart
  gomintapa/lib/src/models/user_model.dart
  gomintapa/lib/src/providers/feed_provider.dart
  gomintapa/lib/src/providers/user_provider.dart
  gomintapa/lib/src/screens/my/mypage.dart
  gomintapa/lib/src/widgets/sections/my/concern_feed_section.dart
  gomintapa/lib/src/widgets/sections/my/concern_tab_bar.dart
  gomintapa/lib/src/widgets/sections/my/concern_tab_bar_view.dart
  gomintapa/pubspec.yaml
Labels: 🐛fixBug, 🎨ui, ✨feat, 🌟frontend

#93 refactor: PhotoAttachment에서 InkWell로 감싸 터치 가능한 영역으로 변경
  gomintapa/lib/src/widgets/forms/input/photo_attachment.dart
Labels: ♻️refactor, 🌟frontend

#96 refactor: 필터바를 home으로 옮겨 중복 코드 없앰
  gomintapa/lib/src/home.dart
  gomintapa/lib/src/screens/feed/feed_index.dart
  gomintapa/lib/src/screens/feed/mak_feed_index.dart
  gomintapa/lib/src/screens/feed/tang_feed_index.dart
  gomintapa/lib/src/widgets/navigation/home_app_bar.dart
Labels: ♻️refactor, 🌟frontend

#100 refactor: 투표율 차이 값 코드 분리 #99
  gomintapa/lib/src/screens/feed/mak_feed_index.dart
  gomintapa/lib/src/widgets/listitems/mak_list_item.dart
Labels: ♻️refactor, 🌟frontend

#102 feat: PhotoAttachment 위젯에 이미지 선택 기능 구현
  gomintapa/lib/src/screens/post/create_post.dart
  gomintapa/lib/src/widgets/forms/input/photo_attachment.dart
  gomintapa/linux/flutter/generated_plugin_registrant.cc
  gomintapa/linux/flutter/generated_plugins.cmake
  gomintapa/macos/Flutter/GeneratedPluginRegistrant.swift
  gomintapa/pubspec.lock
  gomintapa/pubspec.yaml
  gomintapa/windows/flutter/generated_plugin_registrant.cc
  gomintapa/windows/flutter/generated_plugins.cmake
Labels: ✨feat

#104 UI: 고민 카드 선택 영역 사다리꼴로 모양 변경
  gomintapa/lib/src/widgets/cards/card_bottom_section.dart
  gomintapa/lib/src/widgets/cards/card_section.dart
  gomintapa/lib/src/widgets/cards/card_top_section.dart
  gomintapa/lib/src/widgets/cards/trapezoid_option.dart
  gomintapa/lib/src/widgets/listitems/concern_list_item.dart
  gomintapa/lib/src/widgets/listitems/mak_list_item.dart
  gomintapa/lib/src/widgets/listitems/tang_list_item.dart
Labels: 🎨ui, 🌟frontend

#105 Feat/95 : DB와 투표 연결 성공
  gomintapa/lib/src/controllers/feed_controller.dart
  gomintapa/lib/src/providers/feed_provider.dart
  gomintapa/lib/src/screens/post/post_detail.dart
Labels: ✨feat, 🌟frontend, 🔥backend

#108 투표 에러 메시지 안뜨게 하기
  gomintapa/lib/src/controllers/feed_controller.dart
Labels: ♻️refactor

#111 UI: 투표 시 선택한 항목에 효과 구현
  gomintapa/lib/src/screens/post/post_detail.dart
  gomintapa/lib/src/widgets/sections/display/choices/choices_section.dart
Labels: 🎨ui, 🌟frontend

#113 feat: 게시글에 적용한 키워드 뜨게 하기
  gomintapa/lib/src/controllers/feed_controller.dart
  gomintapa/lib/src/models/feed_model.dart
  gomintapa/lib/src/providers/feed_provider.dart
  gomintapa/lib/src/screens/post/create_post.dart
  gomintapa/lib/src/screens/post/post_detail.dart
Labels: ✨feat
